In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("C:\\Users\devri\Desktop\datasets\\boston.csv")
df = data.copy()
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

- **1) CRIM:** per capita crime rate by town
- **2) ZN:** proportion of residential land zoned for lots over 25,000 sq.ft.
- **3) INDUS:** proportion of non-retail business acres per town
- **4) CHAS:** Charles River dummy variable (1 if tract bounds river; 0 otherwise)
- **5) NOX:** nitric oxides concentration (parts per 10 million) [parts/10M]
- **6) RM:** average number of rooms per dwelling
- **7) AGE:** proportion of owner-occupied units built prior to 1940
- **8) DIS:** weighted distances to five Boston employment centres
- **9) RAD:** index of accessibility to radial highways
- **10) TAX:** full-value property-tax rate per $10,000 [$/10k]
- **11) PTRATIO:** pupil-teacher ratio by town
- **12) B:** The result of the equation B=1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
- **13) LSTAT:** % lower status of the population

*Output variable:*
- **1) PRICE:** Median value of owner-occupied homes in $1000's [k$]

In [3]:
df["PRICE"] = df["MEDV"]
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9,11.9

In [4]:
df = df.drop(["MEDV"], axis=1)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CRIM,506.0,3.613524,8.601545,0.00632,0.082045,0.25651,3.677083,88.9762
ZN,506.0,11.363636,23.322453,0.00000,0.000000,0.00000,12.500000,100.0000
INDUS,506.0,11.136779,6.860353,0.46000,5.190000,9.69000,18.100000,27.7400
CHAS,506.0,0.069170,0.253994,0.00000,0.000000,0.00000,0.000000,1.0000
NOX,506.0,0.554695,0.115878,0.38500,0.449000,0.53800,0.624000,0.8710
RM,506.0,6.284634,0.702617,3.56100,5.885500,6.20850,6.623500,8.7800
AGE,506.0,68.574901,28.148861,2.90000,45.025000,77.50000,94.075000,100.0000
DIS,506.0,3.795043,2.105710,1.12960,2.100175,3.20745,5.188425,12.1265
RAD,506.0,9.549407,8.707259,1.00000,4.000000,5.00000,24.000000,24.0000
TAX,506.0,408.237154,168.537116,187.00000,279.000000,330.00000,666.000000,711.0000
PTRATIO,506.0,18.455534,2.164946,12.60000,17.400000,19.05000,20.200000,22.0000
B,506.0,356.674032,91.294864,0.32000,375.377500,391.44000,396.225000,396.9000
LSTAT,506.0,12.653063,7.141062,1.73000,6.950000,11.36000,16.955000,37.9700
PRICE,506.0,22.532806,9.197104,5.00000,17.025000,21.20000,25.000000,50.0000

In [6]:
df.shape

(506, 14)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  PRICE    506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [8]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [9]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]

In [10]:
print(y)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
print(X_train)

[[3.5809e-01 0.0000e+00 6.2000e+00 ... 1.7400e+01 3.9170e+02 9.7100e+00]
 [1.5876e-01 0.0000e+00 1.0810e+01 ... 1.9200e+01 3.7694e+02 9.8800e+00]
 [1.1329e-01 3.0000e+01 4.9300e+00 ... 1.6600e+01 3.9125e+02 1.1380e+01]
 ...
 [1.5098e-01 0.0000e+00 1.0010e+01 ... 1.7800e+01 3.9451e+02 1.0300e+01]
 [2.2927e-01 0.0000e+00 6.9100e+00 ... 1.7900e+01 3.9274e+02 1.8800e+01]
 [1.3914e-01 0.0000e+00 4.0500e+00 ... 1.6600e+01 3.9690e+02 1.4690e+01]]

In [13]:
print(X_test)

[[6.7240e-02 0.0000e+00 3.2400e+00 ... 1.6900e+01 3.7521e+02 7.3400e+00]
 [9.2323e+00 0.0000e+00 1.8100e+01 ... 2.0200e+01 3.6615e+02 9.5300e+00]
 [1.1425e-01 0.0000e+00 1.3890e+01 ... 1.6400e+01 3.9374e+02 1.0500e+01]
 ...
 [1.4932e-01 2.5000e+01 5.1300e+00 ... 1.9700e+01 3.9511e+02 1.3150e+01]
 [1.4052e-01 0.0000e+00 1.0590e+01 ... 1.8600e+01 3.8581e+02 9.3800e+00]
 [1.2802e-01 0.0000e+00 8.5600e+00 ... 2.0900e+01 3.9524e+02 1.2270e+01]]

In [14]:
print(y_train)

[26.7 21.7 22.  22.9 10.4 21.9 20.6 26.4 41.3 17.2 27.1 20.4 16.5 24.4
  8.4 23.   9.7 50.  30.5 12.3 19.4 21.2 20.3 18.8 33.4 18.5 19.6 33.2
 13.1  7.5 13.6 17.4  8.4 35.4 24.  13.4 26.2  7.2 13.1 24.5 37.2 25.
 24.1 16.6 32.9 36.2 11.   7.2 22.8 28.7 14.4 24.4 18.1 22.5 20.5 15.2
 17.4 13.6  8.7 18.2 35.4 31.7 33.  22.2 20.4 23.9 25.  12.7 29.1 12.
 17.7 27.  20.6 10.2 17.5 19.7 29.8 20.5 14.9 10.9 19.5 22.7 19.5 24.6
 25.  24.5 50.  14.3 11.8 31.  28.7 16.2 43.5 25.  22.  19.9 22.1 46.
 22.9 20.2 43.1 34.6 13.8 24.3 21.5 24.4 21.2 23.8 26.6 25.1  9.6 19.4
 19.4  9.5 14.  26.5 13.8 34.7 16.3 21.7 17.5 15.6 20.9 21.7 12.7 18.5
 23.7 19.3 12.7 21.6 23.2 29.6 21.2 23.8 17.1 22.  36.5 18.8 21.9 23.1
 20.2 17.4 37.  24.1 36.2 15.7 32.2 13.5 17.9 13.3 11.7 41.7 18.4 13.1
 25.  21.2 16.  34.9 25.2 24.8 21.5 23.4 18.9 10.8 21.  27.5 17.5 13.5
 28.7 14.8 19.1 28.6 13.1 19.  11.3 13.3 22.4 20.1 18.2 22.9 20.6 25.
 12.8 34.9 23.7 50.  29.  30.1 22.  15.6 23.3 30.1 14.3 22.8 50.  20.8
  6.3 34.9 32.4 19.9 20.3 17.8 23.1 20.4 23.2  7.  16.8 46.7 50.  22.9
 23.9 21.4 21.7 15.4 15.3 23.1 23.9 19.4 11.9 17.8 31.5 33.8 20.8 19.8
 22.4  5.  24.5 19.4 15.1 18.2 19.3 27.1 20.7 37.6 11.7 33.4 30.1 21.4
 45.4 20.1 20.8 26.4 10.4 21.8 32.  21.7 18.4 37.9 17.8 28.  28.2 36.
 18.9 15.  22.5 30.7 20.  19.1 23.3 26.6 21.1 19.7 20.  12.1  7.2 14.2
 17.3 27.5 22.2 10.9 19.2 32.  14.5 24.7 12.6 24.  24.1 50.  16.1 43.8
 26.6 36.1 21.8 29.9 50.  44.  20.6 19.6 28.4 19.1 22.3 20.9 28.4 14.4
 32.7 13.8  8.5 22.5 35.1 31.6 17.8 15.6 20.7 39.8 17.8 19.6 14.9 22.
 48.8 25.  48.5 23.9 20.3 15.2 10.5 19.  16.4  8.8 22.  24.8 50.  19.3
 22.7 37.3 31.6  8.3 23.1 50.  13.9 16.1 25.3 19.5 10.2 19.9 35.2 13.4
 24.7 11.5 23.4 16.7 15.4 18.  28.5 18.4 32.5 50.  50.  19.6 17.6 42.3
 14.5 13.2 16.2 29.6 16.7 13.  22.3 13.4  5.  19.5 14.6 22.   8.1 24.6
 33.2 20.6 14.1 14.1 21.1 30.3 23.7 21.4 18.3  8.5 22.8 22.8 22.2 13.9
 25.  18.5  7.  22.6 20.1 30.8 31.1 23.8 12.5 23.6 23.2 24.2 22.2 27.9
 22.2 33.1 19.3 18.9 22.6 50.  24.8 18.5 36.4 19.2 16.6 23.1]

In [15]:
print(y_test)

[22.6 50.  23.   8.3 21.2 19.9 20.6 18.7 16.1 18.6  8.8 17.2 14.9 10.5
 50.  29.  23.  33.3 29.4 21.  23.8 19.1 20.4 29.1 19.3 23.1 19.6 19.4
 38.7 18.7 14.6 20.  20.5 20.1 23.6 16.8  5.6 50.  14.5 13.3 23.9 20.
 19.8 13.8 16.5 21.6 20.3 17.  11.8 27.5 15.6 23.1 24.3 42.8 15.6 21.7
 17.1 17.2 15.  21.7 18.6 21.  33.1 31.5 20.1 29.8 15.2 15.  27.5 22.6
 20.  21.4 23.5 31.2 23.7  7.4 48.3 24.4 22.6 18.3 23.3 17.1 27.9 44.8
 50.  23.  21.4 10.2 23.3 23.2 18.9 13.4 21.9 24.8 11.9 24.3 13.8 24.7
 14.1 18.7 28.1 19.8]

In [16]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [17]:
"""from xgboost import XGBRegressor
model = XGBRegressor(objective='reg:squarederror')
model.fit(X_train,y_train)"""

"from xgboost import XGBRegressor\nmodel = XGBRegressor(objective='reg:squarederror')\nmodel.fit(X_train,y_train)"

In [19]:
pred = regressor.predict(X_test)

In [20]:
from sklearn import metrics
metrics.r2_score(y_test,pred)

0.7424705927235331

In [21]:
metrics.mean_absolute_error(y_test,pred)

2.7758823529411765

In [22]:
metrics.mean_squared_error(y_test,pred)

20.970217647058828